spring:

  application:
    name: biedronka_saver

  datasource:
    url: jdbc:postgresql://localhost:5432/biedronka
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  web:
    locale: en
    locale-resolver: accept_header

fronted:
  url: http://localhost:3000

server:
  port: 8080

token:
  signing:
    key: "your-256-bit-secret-your-256-bit-secret"
  expiration:
    time:
      seconds: 86400